name: "Build and Release APK"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    env:
      RELEASE_PATH: "releases/"
      MODE: "release"
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.1'
      - run: flutter pub get
      - run: flutter build apk

      - name: Release
        id: build_package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["releases","master"]'

      - name: Released version
        if: steps.build_package.outputs.released == 'true'
        run: |
          echo released version: ${{ steps.build_package.outputs.version }}

      - name: Output
        if: steps.build_package.outputs.released == 'true'
        run: |
          echo released version: ${{ steps.build_package.outputs.version }}, type: ${{ steps.build_package.outputs.level }}
