name: "Build and Release APK"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    env:
      RELEASE_PATH: "releases/"
      MODE: "release"
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.1'
      - run: flutter pub get
      - run: flutter build apk

      - name: Show apk
        run: |
          pwd
          ls build/app/outputs/apk/${{ env.MODE }}/

      - name: "Build & test"
        run: |
          echo "done!"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["releases","master"]'

      - name: Outputs
        run: |
          echo data:
          echo released version: ${{ steps.build_package.outputs.version }}
          echo released version: ${{ steps.build_package.outputs.released }}
          echo released version: ${{ fromJson(steps) }}

      - name: Output
        if: steps.build_package.outputs.released == 'true'
        run: |
          echo released version: ${{ steps.build_package.outputs.version }}, type: ${{ steps.build_package.outputs.level }}

#      - name: Bump version and push tag
#        uses: anothrNick/github-tag-action@1.17.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          WITH_V: true

#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: true
#          title: "Development Build"
#          files: |
#            build/app/outputs/apk/debug/*.apk
